### ISSUE TITLE
Need a help

### ISSUE THREAD

**Issue by Shreyas-sonu** [filoscoder/react-hls-video-player#57]
hi your project was so helpful for me, I just need to create an hls instance In my react application to play m3u8 file, please reply me if u can help

**Comment by filoscoder** [comment]
Hi @Shreyas-sonu, I'm not quite sure what you need exactly to be helped.
But, you can see a reference of how the HLS instance is handled [here](https://github.com/filoscoder/react-hls-video-player/blob/main/src/components/CustomVideoPlayer/HlsPlayer/index.tsx)

**Comment by Shreyas-sonu** [comment]
does hls.js provide quality selector options out of the box?

**Comment by filoscoder** [comment]
In Hls what you call `quality` is called `level`.
They provide an [API](https://github.com/video-dev/hls.js/blob/master/docs/API.md#quality-switch-control-api) to update this value, but the available qualities (levels) depend on the video file it is playing.

**Comment by Shreyas-sonu** [comment]
I am trying to implement Video.js in my streaming app where it should able to play adaptive bitrate streaming, the issue I am unable to add Quality selector menu in control bar to switch resolution, also unable to add synthetic events like onClick Key down etc.

This is my code

import { useEffect, useRef, useState } from "react";
import VideoJS from "./VideoJS";
import "videojs-hls-quality-selector";

const Video = () => {
const playerRef = useRef(null);
const [player, setPlayer] = useState(null);
const videoJsOptions = {
autoplay: true,
controls: true,
responsive: true,
height: "500px",
disablePictureInPicture: true,
enableSmoothSeeking: true,
experimentalSvgIcons: true,
playbackRates: [0.5, 0.75, 1, 1.5, 2],
controlBar: {
components: {
qualityMenuButton: {},
},
skipButtons: {
backward: 10,
forward: 10,
},
},
userActions: {
hotkeys: true,
},
sources: [
{
src: "http://192.168.1.139:5000/hls/subject27/video-chunk/video-chunk_master.m3u8",
type: "application/x-mpegURL",
},
],
};
const handlePlayerReady = data => {
playerRef.current = data;
setPlayer(data);
};
useEffect(() => {
if (player) {
player.hlsQualitySelector({ displayCurrentQuality: true });
}
}, [player]);
return (



);
};
export default Video;

import React from "react";
import videojs from "video.js";
import "video.js/dist/video-js.css";
import "@videojs/themes/dist/city/index.css";

export const VideoJS = props => {
const videoRef = React.useRef(null);
const playerRef = React.useRef(null);
const { options, onReady } = props;

React.useEffect(() => {
if (!playerRef.current) {
const videoElement = document.createElement("video-js");
videoElement.classList.add("vjs-big-play-centered");
videoRef.current.appendChild(videoElement);

  const player = (playerRef.current = videojs(videoElement, options, () => {
    videojs.log("player is ready");
    onReady && onReady(player);
  }));
} else {
  const player = playerRef.current;
  player.autoplay(options.autoplay);
  player.src(options.sources);
}
}, [options, videoRef]);

React.useEffect(() => {
const player = playerRef.current;
return () => {
if (player && !player.isDisposed()) {
player.dispose();
playerRef.current = null;
}
};
}, [playerRef]);

return (



);
};
export default VideoJS;

so this is the error

**Comment by filoscoder** [comment]
> I am trying to implement Video.js in my streaming app where it should able to play adaptive bitrate streaming, the issue I am unable to add Quality selector menu in control bar to switch resolution, also unable to add synthetic events like onClick Key down etc.
> 
> This is my code
> 
> import { useEffect, useRef, useState } from "react"; import VideoJS from "./VideoJS"; import "videojs-hls-quality-selector";
> 
> const Video = () => { const playerRef = useRef(null); const [player, setPlayer] = useState(null); const videoJsOptions = { autoplay: true, controls: true, responsive: true, height: "500px", disablePictureInPicture: true, enableSmoothSeeking: true, experimentalSvgIcons: true, playbackRates: [0.5, 0.75, 1, 1.5, 2], controlBar: { components: { qualityMenuButton: {}, }, skipButtons: { backward: 10, forward: 10, }, }, userActions: { hotkeys: true, }, sources: [ { src: "http://192.168.1.139:5000/hls/subject27/video-chunk/video-chunk_master.m3u8", type: "application/x-mpegURL", }, ], }; const handlePlayerReady = data => { playerRef.current = data; setPlayer(data); }; useEffect(() => { if (player) { player.hlsQualitySelector({ displayCurrentQuality: true }); } }, [player]); return (
> 
> ); }; export default Video;
> 
> import React from "react"; import videojs from "video.js"; import "video.js/dist/video-js.css"; import "@videojs/themes/dist/city/index.css";
> 
> export const VideoJS = props => { const videoRef = React.useRef(null); const playerRef = React.useRef(null); const { options, onReady } = props;
> 
> React.useEffect(() => { if (!playerRef.current) { const videoElement = document.createElement("video-js"); videoElement.classList.add("vjs-big-play-centered"); videoRef.current.appendChild(videoElement);
> 
> const player = (playerRef.current = videojs(videoElement, options, () => { videojs.log("player is ready"); onReady && onReady(player); })); } else { const player = playerRef.current; player.autoplay(options.autoplay); player.src(options.sources); } }, [options, videoRef]);
> 
> React.useEffect(() => { const player = playerRef.current; return () => { if (player && !player.isDisposed()) { player.dispose(); playerRef.current = null; } }; }, [playerRef]);
> 
> return (
> 
> ); }; export default VideoJS;
> 
> so this is the error ![image](https://private-user-images.githubusercontent.com/111351684/330023789-29b6e47c-5f35-4c41-bd6c-87e26247f5d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDMyMDIsIm5iZiI6MTcxNTYwMjkwMiwicGF0aCI6Ii8xMTEzNTE2ODQvMzMwMDIzNzg5LTI5YjZlNDdjLTVmMzUtNGM0MS1iZDZjLTg3ZTI2MjQ3ZjVkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMjIxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjhjMDQ3MDAwZTBhZjRiZWU2YTg1Y2IwNTA2ODc4ODVlZTFiZDliMzhhMjA5ZDAwZDQ1MWE5YjVlZDY2MWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.alpIKR80LA39CdfO4RJbgCZnfBa3K166bRHmJEhXX8w) because of this code (in first component Video.jsx) import "videojs-hls-quality-selector"; useEffect(() => { if (player) { player.hlsQualitySelector({ displayCurrentQuality: true }); } }, [player]);
> 
> This is the version of vJs and plugin I am using "video.js": "^8.12.0", "videojs-hls-quality-selector": "^2.0.0"
> 
> Please Help me with this

Sorry, this is not related with this project. You should ask in their's issue board. Thanks
